name: Run Tests and Determine Code Coverage

on: [pull_request, workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.11"
          environment-file: environment.yml
          activate-environment: pyinla

      - name: Install package in editable mode
        run: |
          conda init
          conda activate pyinla
          pip install -e .

      - name: Run tests
        run: |
          conda activate pyinla
          pytest --cov=src/pyinla --cov-report=term --cov-report=xml tests/
      
      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
